-- Diagnostic: Compare CATGOR_OLD_CATEGORY vs CATGOR_CODE

-- 1. Check if values are different
SELECT
    CATGOR_CODE,
    CATGOR_OLD_CATEGORY,
    CATGOR_CATALOG_ROLLUP,
    CASE
        WHEN CATGOR_CODE = CATGOR_OLD_CATEGORY THEN 'SAME'
        ELSE 'DIFFERENT'
    END AS Comparison
FROM dbo.CATGOR
WHERE LTRIM(RTRIM(ISNULL(CATGOR_CATALOG_ROLLUP, ''))) <> ''
ORDER BY Comparison DESC, CATGOR_CATALOG_ROLLUP;

-- 2. Check for duplicates in CATGOR_CODE
SELECT
    CATGOR_CODE,
    COUNT(*) AS RowCount
FROM dbo.CATGOR
WHERE LTRIM(RTRIM(ISNULL(CATGOR_CATALOG_ROLLUP, ''))) <> ''
GROUP BY CATGOR_CODE
HAVING COUNT(*) > 1;

-- 3. Check for duplicates in CATGOR_OLD_CATEGORY
SELECT
    CATGOR_OLD_CATEGORY,
    COUNT(*) AS RowCount
FROM dbo.CATGOR
WHERE LTRIM(RTRIM(ISNULL(CATGOR_CATALOG_ROLLUP, ''))) <> ''
GROUP BY CATGOR_OLD_CATEGORY
HAVING COUNT(*) > 1;

-- 4. Check customer categories that don't match CATGOR_CODE
SELECT DISTINCT
    c.CUSTCATEGORY,
    cg_code.CATGOR_CODE AS MatchesCATGOR_CODE,
    cg_old.CATGOR_OLD_CATEGORY AS MatchesCATGOR_OLD_CATEGORY
FROM dbo.cust c
LEFT JOIN dbo.CATGOR cg_code
    ON LTRIM(RTRIM(cg_code.CATGOR_CODE)) = LTRIM(RTRIM(c.CUSTCATEGORY))
LEFT JOIN dbo.CATGOR cg_old
    ON LTRIM(RTRIM(cg_old.CATGOR_OLD_CATEGORY)) = LTRIM(RTRIM(c.CUSTCATEGORY))
WHERE c.CUSTMEMBERNUM IS NOT NULL
    AND (cg_code.CATGOR_CODE IS NULL OR cg_old.CATGOR_OLD_CATEGORY IS NULL)
ORDER BY c.CUSTCATEGORY;

-- 5. Count catalogs with CATGOR_OLD_CATEGORY (your working query)
WITH CustomersWithIndividualPricing AS (
    SELECT DISTINCT sp.SPECPR_KEY AS CUSTID
    FROM dbo.specpr sp
    WHERE sp.SPECPR_TYPE = 'CI'
        AND sp.SPECPR_APPROVER IS NOT NULL
        AND LTRIM(RTRIM(sp.SPECPR_APPROVER)) <> ''
        AND sp.SPECPR_EXPIRE_DATE > GETDATE()
)
SELECT
    'Using CATGOR_OLD_CATEGORY' AS Method,
    COUNT(DISTINCT LTRIM(RTRIM(c.CUSTGROUPCODE))) AS UniqueGroupCodes,
    COUNT(DISTINCT CONCAT(
        LTRIM(RTRIM(cg.CATGOR_CATALOG_ROLLUP)), '|',
        CASE WHEN ISNULL(c.CUSTPRICETIER, 0) = 0 THEN '1' ELSE LTRIM(RTRIM(c.CUSTPRICETIER)) END, '|',
        LTRIM(RTRIM(c.CUSTGROUPCODE))
    )) AS UniqueBuyingGroupCatalogs
FROM dbo.cust c
INNER JOIN dbo.CATGOR cg WITH (NOLOCK)
    ON LTRIM(RTRIM(cg.CATGOR_OLD_CATEGORY)) = LTRIM(RTRIM(c.CUSTCATEGORY))
LEFT JOIN CustomersWithIndividualPricing ci ON c.CUSTID = ci.CUSTID
WHERE c.CUSTID IS NOT NULL
    AND ci.CUSTID IS NULL
    AND LTRIM(RTRIM(ISNULL(c.CUSTCATEGORY, ''))) <> ''
    AND c.CUSTMEMBERNUM IS NOT NULL
    AND LTRIM(RTRIM(ISNULL(cg.CATGOR_CATALOG_ROLLUP, ''))) <> ''
    AND LTRIM(RTRIM(ISNULL(c.CUSTGROUPCODE, ''))) <> '';

-- 6. Count catalogs with CATGOR_CODE (problematic query)
WITH CustomersWithIndividualPricing AS (
    SELECT DISTINCT sp.SPECPR_KEY AS CUSTID
    FROM dbo.specpr sp
    WHERE sp.SPECPR_TYPE = 'CI'
        AND sp.SPECPR_APPROVER IS NOT NULL
        AND LTRIM(RTRIM(sp.SPECPR_APPROVER)) <> ''
        AND sp.SPECPR_EXPIRE_DATE > GETDATE()
)
SELECT
    'Using CATGOR_CODE' AS Method,
    COUNT(DISTINCT LTRIM(RTRIM(c.CUSTGROUPCODE))) AS UniqueGroupCodes,
    COUNT(DISTINCT CONCAT(
        LTRIM(RTRIM(cg.CATGOR_CATALOG_ROLLUP)), '|',
        CASE WHEN ISNULL(c.CUSTPRICETIER, 0) = 0 THEN '1' ELSE LTRIM(RTRIM(c.CUSTPRICETIER)) END, '|',
        LTRIM(RTRIM(c.CUSTGROUPCODE))
    )) AS UniqueBuyingGroupCatalogs
FROM dbo.cust c
INNER JOIN dbo.CATGOR cg WITH (NOLOCK)
    ON LTRIM(RTRIM(cg.CATGOR_CODE)) = LTRIM(RTRIM(c.CUSTCATEGORY))
LEFT JOIN CustomersWithIndividualPricing ci ON c.CUSTID = ci.CUSTID
WHERE c.CUSTID IS NOT NULL
    AND ci.CUSTID IS NULL
    AND LTRIM(RTRIM(ISNULL(c.CUSTCATEGORY, ''))) <> ''
    AND c.CUSTMEMBERNUM IS NOT NULL
    AND LTRIM(RTRIM(ISNULL(cg.CATGOR_CATALOG_ROLLUP, ''))) <> ''
    AND LTRIM(RTRIM(ISNULL(c.CUSTGROUPCODE, ''))) <> '';
